fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "ok@ok.com"
        sender_name: "Sender"
    registration:
        form:
            type: App\Form\RegistrationFormType